[package]
name = "price-predict"
version = "0.1.0"
description = "Created with Anchor"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "price_predict"

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
chainlink_solana = { workspace = true }
