[package]
name = "jackpot-lottery"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "jackpot_lottery"

[dependencies]
anchor-lang = { workspace = true, features = [ "init-if-needed" ] }
anchor-spl = { workspace = true }
vrf-lib = { workspace = true }
sha3 = { version = "0.10", default-features = false }
